### ISSUE TITLE
Add documentation for how to convert to a domain object

### ISSUE THREAD

**Issue by joevandyk** [rom-rb/rom-http#11]
In the example in the README right now, calling `container.relation(:users).by_id(1)` returns a hash. It would be nice to see how to get some sort of domain object back.

**Comment by hmadison** [comment]
See [Mapping to custom objects](http://rom-rb.org/learn/read/simple/#mapping-to-custom-objects).

**Comment by cflipse** [comment]
I will note that documentation improvement is definatly needed.  This gem is still in an early, rough state.

**Comment by joevandyk** [comment]
I saw that section, but I'm still confused.

**Comment by solnic** [comment]
Which part is confusing? Assuming you've got a repo configured to use `:users` relation, you simply do `users.by_id(1).as(YourUserClass)`.

**Comment by joevandyk** [comment]
Ah, perfect. Thanks. 

Not sure if I'm blind, but can't see where `as` is mentioned in that page.

**Comment by solnic** [comment]
It is mentioned :) Anyhow, a more comprehensive guide will be written as soon as I'm done with new rom-sql and rom-repository versions.

**Comment by solnic** [comment]
Closing as this is outdated. User docs are still pending, even after 3 years. Oh well. There's an issue about it in rom-rb/rom-rb.org#279
