### ISSUE TITLE
Dataset should produce it's own URL

### ISSUE THREAD

**Issue by cflipse** [rom-rb/rom-http#16]
Rather than relying on users correctly assembling the parts of a request URI in the request_handler, dataset should be able to build it's own URI.

**Comment by AMHOL** [comment]
This was done in https://github.com/rom-rb/rom-http/commit/80d7aac51c0f011f6515934d51212e4f2cc651a8 but I forgot to update the example https://github.com/rom-rb/rom-http/blob/master/examples/repository_with_combine.rb
