### ISSUE TITLE
Release v0.6.0 has the wrong 'rom' dependency

### ISSUE THREAD

**Issue by streppa-ent** [rom-rb/rom-http#33]
Looks like this has already been fixed in the repo. It just needs to get tagged and pushed to the gem hosts.

> https://rubygems.org/gems/rom-http/
VERSIONS:
0.6.0 - February 07, 2017 (18.5 KB)
0.6.0.rc1 - January 28, 2017 (18.5 KB)
0.5.0 - August 08, 2016 (17 KB)
0.4.0 - April 30, 2016 (15.5 KB)
0.3.0 - March 17, 2016 (15 KB)
Show all versions (11 total)

> RUNTIME DEPENDENCIES (4):
concurrent-ruby >= 0
dry-core >= 0.2.3, ~> 0.2
dry-equalizer ~> 0.2
**rom ~> 3.0.0**

> DEVELOPMENT DEPENDENCIES (4):
bundler >= 0
rake ~> 10.0
rspec ~> 3.1
rspec-its >= 0

**Comment by maximderbin** [comment]
@streppa-ent what do you mean by `wrong` rom? v.0.6 suppose to work with rom 3 not rom 4.

rom is upgraded to 4th version in master but @solnic still want to follow up with some additional changes as per https://github.com/rom-rb/rom-http/pull/32 before we'll be able to tag and release it.

**Comment by streppa-ent** [comment]
Yeah... I just read that. Please disregard.
